name: build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Build
      run: |
        echo "\nsentryDsn=${{secrets.INTELLIJ_PLUGIN_SENTRY_DSN}}" >> src/main/resources/config.properties
        ./gradlew buildPlugin

    - name: Push to Coding Artifacts
      if: ${{ github.ref == 'refs/heads/main'}}
      run: |
        cd build/distributions/
        PLUGIN_ZIP=$(ls | grep nocalhost-intellij-plugin-)
        curl -T ${PLUGIN_ZIP} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/plugins/nocalhost-intellij-plugin.zip?version=main"

    - name: Push to Coding Artifacts
      if: ${{ github.ref == 'refs/heads/dev'}}
      run: |
        cd build/distributions/
        PLUGIN_ZIP=$(ls | grep nocalhost-intellij-plugin-)
        curl -T ${PLUGIN_ZIP} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/plugins/nocalhost-intellij-plugin.zip?version=dev"

    - name: Push to Coding Artifacts
      run: |
        cd build/distributions/
        PLUGIN_ZIP=$(ls | grep nocalhost-intellij-plugin-)
        curl -T ${PLUGIN_ZIP} -u ${{ secrets.CODING_ARTIFACTS_USER }}:${{ secrets.CODING_ARTIFACTS_PASS }} "https://codingcorp-generic.pkg.coding.net/nocalhost/plugins/nocalhost-intellij-plugin.zip?version=${GITHUB_SHA}"